# Use postgres/example user/password credentials
version: '3.1'

services:
  db:
    image: postgres
    environment:
      POSTGRES_USER: sarmuns
      POSTGRES_DB: trabweb
      POSTGRES_PASSWORD: docker
    ports:
      - 5432:5432
      